services:
  - type: web
    name: classroom-reservation
    env: python
    region: ohio
    buildCommand: pip install -r requirements.txt
    startCommand: sleep 5 && python migrate.py && gunicorn app:app
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: RENDER
        value: true
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: classroom_db
          property: connectionString

databases:
  - name: classroom_db
    plan: free
    region: ohio
    databaseName: classroom_reservation
    ipAllowList: []  # only allow internal connections 